/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-29 01:10:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SHAREGRAM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Sharegram/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666788936298L));
    _jspx_dependants.put("/WEB-INF/views/layout/footer.jsp", Long.valueOf(1672273067560L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("SHAREGRAM에 오신 것을 환영합니다.", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Begin Page Content -->\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Page Heading -->\r\n");
      out.write("                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("                        <h1 class=\"h3 mb-0 text-gray-800\">야야야야야야야야 아닙니다 전혀 아닝에요</h1>\r\n");
      out.write("                        <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\"><i\r\n");
      out.write("                                class=\"fas fa-download fa-sm text-white-50\"></i> Generate Report</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Content Row -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-primary shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">\r\n");
      out.write("                                                Earnings (Monthly)</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">$40,000</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">\r\n");
      out.write("                                                Earnings (Annual)</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">$215,000</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-dollar-sign fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">Tasks\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                                <div class=\"col-auto\">\r\n");
      out.write("                                                    <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">50%</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col\">\r\n");
      out.write("                                                    <div class=\"progress progress-sm mr-2\">\r\n");
      out.write("                                                        <div class=\"progress-bar bg-info\" role=\"progressbar\"\r\n");
      out.write("                                                            style=\"width: 50%\" aria-valuenow=\"50\" aria-valuemin=\"0\"\r\n");
      out.write("                                                            aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Pending Requests Card Example -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"card border-left-warning shadow h-100 py-2\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                                        <div class=\"col mr-2\">\r\n");
      out.write("                                            <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">\r\n");
      out.write("                                                Pending Requests</div>\r\n");
      out.write("                                            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">18</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-auto\">\r\n");
      out.write("                                            <i class=\"fas fa-comments fa-2x text-gray-300\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Content Row -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Area Chart -->\r\n");
      out.write("                        <div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <!-- Card Header - Dropdown -->\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Earnings Overview</h6>\r\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\r\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\r\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card Body -->\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"chart-area\">\r\n");
      out.write("                                        <canvas id=\"myAreaChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Pie Chart -->\r\n");
      out.write("                        <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <!-- Card Header - Dropdown -->\r\n");
      out.write("                                <div\r\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Revenue Sources</h6>\r\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\r\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\r\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card Body -->\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"chart-pie pt-4 pb-2\">\r\n");
      out.write("                                        <canvas id=\"myPieChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mt-4 text-center small\">\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-primary\"></i> Direct\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-success\"></i> Social\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"mr-2\">\r\n");
      out.write("                                            <i class=\"fas fa-circle text-info\"></i> Referral\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Content Row -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Content Column -->\r\n");
      out.write("                        <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Project Card Example -->\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <div class=\"card-header py-3\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Projects</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Server Migration <span\r\n");
      out.write("                                            class=\"float-right\">20%</span></h4>\r\n");
      out.write("                                    <div class=\"progress mb-4\">\r\n");
      out.write("                                        <div class=\"progress-bar bg-danger\" role=\"progressbar\" style=\"width: 20%\"\r\n");
      out.write("                                            aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Sales Tracking <span\r\n");
      out.write("                                            class=\"float-right\">40%</span></h4>\r\n");
      out.write("                                    <div class=\"progress mb-4\">\r\n");
      out.write("                                        <div class=\"progress-bar bg-warning\" role=\"progressbar\" style=\"width: 40%\"\r\n");
      out.write("                                            aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Customer Database <span\r\n");
      out.write("                                            class=\"float-right\">60%</span></h4>\r\n");
      out.write("                                    <div class=\"progress mb-4\">\r\n");
      out.write("                                        <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 60%\"\r\n");
      out.write("                                            aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Payout Details <span\r\n");
      out.write("                                            class=\"float-right\">80%</span></h4>\r\n");
      out.write("                                    <div class=\"progress mb-4\">\r\n");
      out.write("                                        <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 80%\"\r\n");
      out.write("                                            aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Account Setup <span\r\n");
      out.write("                                            class=\"float-right\">Complete!</span></h4>\r\n");
      out.write("                                    <div class=\"progress\">\r\n");
      out.write("                                        <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 100%\"\r\n");
      out.write("                                            aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Color System -->\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-primary text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Primary\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#4e73df</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-success text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Success\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#1cc88a</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-info text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Info\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#36b9cc</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-warning text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Warning\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#f6c23e</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-danger text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Danger\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#e74a3b</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-secondary text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Secondary\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#858796</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-light text-black shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Light\r\n");
      out.write("                                            <div class=\"text-black-50 small\">#f8f9fc</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-dark text-white shadow\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            Dark\r\n");
      out.write("                                            <div class=\"text-white-50 small\">#5a5c69</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Illustrations -->\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <div class=\"card-header py-3\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Illustrations</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 25rem;\"\r\n");
      out.write("                                            src=\"img/undraw_posting_photo.svg\" alt=\"...\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>Add some quality, svg illustrations to your project courtesy of <a\r\n");
      out.write("                                            target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">unDraw</a>, a\r\n");
      out.write("                                        constantly updated collection of beautiful svg images that you can use\r\n");
      out.write("                                        completely free and without attribution!</p>\r\n");
      out.write("                                    <a target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">Browse Illustrations on\r\n");
      out.write("                                        unDraw &rarr;</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Approach -->\r\n");
      out.write("                            <div class=\"card shadow mb-4\">\r\n");
      out.write("                                <div class=\"card-header py-3\">\r\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Development Approach</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce\r\n");
      out.write("                                        CSS bloat and poor page performance. Custom CSS classes are used to create\r\n");
      out.write("                                        custom components and custom utility classes.</p>\r\n");
      out.write("                                    <p class=\"mb-0\">Before working with this theme, you should become familiar with the\r\n");
      out.write("                                        Bootstrap framework, especially the utility classes.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; SHAREGRAM 2022</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">Ã</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/demo/chart-pie-demo.js\"></script>\r\n");
      out.write("		");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/index.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
