use vvovovv;

DROP TABLE IF EXISTS APPROVAL;
DROP TABLE IF EXISTS PROF_IMAGE;
DROP TABLE IF EXISTS ACCESS_LOG;
DROP TABLE IF EXISTS NO_TABLE;

DROP TABLE IF EXISTS SUMMERNOTE_IMAGE;
DROP TABLE IF EXISTS ATTACH;
DROP TABLE IF EXISTS UPLOAD;
DROP TABLE IF EXISTS LOVES;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS DEPTHRCOMMENT;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS NOTIC;
DROP TABLE IF EXISTS ANONY;
DROP TABLE IF EXISTS UN_CMT;

DROP TABLE IF EXISTS MAIL_SUMMER_IMAGE;
DROP TABLE IF EXISTS MAIL_ATCH;
DROP TABLE IF EXISTS RECEIVERS;
DROP TABLE IF EXISTS MAIL;
DROP TABLE IF EXISTS PERSONAL_ADDR;
DROP TABLE IF EXISTS ADDR_GROUP;  
DROP TABLE IF EXISTS EMP_ADDR;

DROP TABLE IF EXISTS ATTENDANCE;
DROP TABLE IF EXISTS SCHEDULE;

DROP TABLE IF EXISTS RETIRED;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS EMP_POSITION;

CREATE TABLE EMP_POSITION(
  JOB_NO 		INT(5) NOT NULL AUTO_INCREMENT,
  JOB_NAME 		VARCHAR(10),
  PRIMARY KEY (JOB_NO)
) ;

CREATE TABLE DEPARTMENTS(
  DEPT_NO 		INT(11) NOT NULL AUTO_INCREMENT,
  DEPT_NAME 	VARCHAR(10),
  PRIMARY KEY (DEPT_NO)
) ;

ALTER TABLE DEPARTMENTS AUTO_INCREMENT = 10;

CREATE TABLE NO_TABLE(
	 NO 				INT(8) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (NO)
);

ALTER TABLE NO_TABLE AUTO_INCREMENT = 1;

CREATE TABLE EMPLOYEES(
  EMP_NO 			INT(8) NOT NULL UNIQUE,
  EMP_PW 			VARCHAR(64),
  NAME 				VARCHAR(50),
  BIRTHYEAR 		VARCHAR(4),
  BIRTHDAY 			VARCHAR(4),
  JOIN_DATE 		DATETIME,
  PROF_IMG			VARCHAR(100),
  INFO_MODIFY_DATE 	DATETIME,
  STATUS 			VARCHAR(10),
  SALARY 			INT(11),
  JOB_NO 			INT(5),
  DEPT_NO 			INT(5),
  PHONE				VARCHAR(11) NOT NULL UNIQUE,
  SESSION_ID 		VARCHAR(32),        -- 추가
  SESSION_LIMIT_DATE DATETIME,             -- 추가

  PRIMARY KEY (EMP_NO),
  FOREIGN KEY (JOB_NO) REFERENCES `EMP_POSITION` (JOB_NO) ON DELETE SET NULL,
  FOREIGN KEY (DEPT_NO) REFERENCES `DEPARTMENTS` (DEPT_NO) ON DELETE SET NULL
) ;

CREATE TABLE RETIRED(
  EMP_NO 			INT(8),
  NAME 				VARCHAR(50),
  PHONE 			VARCHAR(11),
  BIRTHYEAR 		VARCHAR(4),
  BIRTHDAY 			VARCHAR(4),
  JOIN_DATE 		DATETIME,
  RETIRED_DATE 		DATETIME,
  JOB_NO 			INT(8),
  DEPT_NO 			INT(8),
  PRIMARY KEY (EMP_NO)
) ;

CREATE TABLE SCHEDULE(
  SCHEDULE_NO 				INT(8) NOT NULL AUTO_INCREMENT,
  EMP_NO 					INT(8),
  SCHEDULE_TITLE 			VARCHAR(100),
  SCHEDULE_START 			VARCHAR(40),
  SCHEDULE_END 				VARCHAR(40),
  SCHEDULE_ALLDAY 			VARCHAR(20),
  PRIMARY KEY (SCHEDULE_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
) ;

CREATE TABLE ATTENDANCE(
  ATT_NO 			INT(8) NOT NULL AUTO_INCREMENT,
  EMP_NO 			INT(8),
  ATT_START 		VARCHAR(40),
  ATT_END 			VARCHAR(40),
  EARLY_STATUS 		VARCHAR(15),
  ATT_STATUS 		VARCHAR(40),
  PRIMARY KEY (ATT_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
) ;

CREATE TABLE EMP_ADDR(
  EMP_ADDR_NO 	INT(8) NOT NULL AUTO_INCREMENT,
  EMP_NO 		INT(8),
  DEPT_NO 		INT(8),
  JOB_NO 		INT(8),
  NAME 			VARCHAR(50),
  PASSWORD 		VARCHAR(20),
  PHONE 		VARCHAR(16),
  EMAIL 		VARCHAR(100),
  FAX 			VARCHAR(20),
  PRIMARY KEY (EMP_ADDR_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE,
  FOREIGN KEY (DEPT_NO) REFERENCES `DEPARTMENTS` (DEPT_NO) ON DELETE SET NULL,
  FOREIGN KEY (JOB_NO) REFERENCES `EMP_POSITION` (JOB_NO) ON DELETE SET NULL
) ;

CREATE TABLE ADDR_GROUP(
  ADDR_GROUP_NO 	INT(8) NOT NULL AUTO_INCREMENT,
  EMP_NO 			INT(8) NOT NULL,
  ADDR_GROUP_NAME 	VARCHAR(36),
  PRIMARY KEY (ADDR_GROUP_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
) ;

CREATE TABLE PERSONAL_ADDR(
  PERSONAL_NO 		INT(8) NOT NULL AUTO_INCREMENT,
  ADDR_GROUP_NO 	INT(8) NOT NULL,
  ADDR_NAME 		VARCHAR(50),
  ADDR_PHONE 		VARCHAR(16),
  COMPANY 			VARCHAR(50),
  EMAIL 			VARCHAR(100),
  FAX 				VARCHAR(20),
  MEMO 				VARCHAR(1000),
  IMPORTANT_CHECK 	VARCHAR(1),
  PRIMARY KEY (PERSONAL_NO),
  FOREIGN KEY (ADDR_GROUP_NO) REFERENCES `ADDR_GROUP` (ADDR_GROUP_NO) ON DELETE CASCADE
) ;

ALTER TABLE PERSONAL_ADDR
    ADD CONSTRAINT
    CHECK (IMPORTANT_CHECK IN ('Y', 'N'));
    
CREATE TABLE MAIL(
  MAIL_NO 		INT(6) NOT NULL AUTO_INCREMENT,
  EMP_NO 		INT(8) NOT NULL,
  SENDER 		VARCHAR(100),
  SUBJECT 		VARCHAR(100),
  MAIL_CONTENT 	LONG,
  SEND_DATE 	DATETIME,
  SEND_STATUS 	VARCHAR(30),
  TAG_NO 		INT,
  PRIMARY KEY (MAIL_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
) ;

CREATE TABLE RECEIVERS(
  REC_EMP_NO 	INT(6) NOT NULL,
  MAIL_NO 		INT(6) NOT NULL,
  READ_CHECK 	VARCHAR(1),
  DELETE_CHECK 	VARCHAR(1),
  RECEIVE_TYPE 	VARCHAR(4),
  FOREIGN KEY (REC_EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE,
  FOREIGN KEY (MAIL_NO) REFERENCES `MAIL` (MAIL_NO) ON DELETE CASCADE
) ;

ALTER TABLE RECEIVERS
    ADD CONSTRAINT
    CHECK (READ_CHECK IN ('Y', 'N'));
    
ALTER TABLE RECEIVERS
    ADD CONSTRAINT
    CHECK (DELETE_CHECK IN ('Y', 'N'));
    
ALTER TABLE RECEIVERS
    ADD CONSTRAINT
    CHECK (RECEIVE_TYPE IN ('To', 'cc', 'send'));
    
CREATE TABLE MAIL_ATCH(
  FILE_NO 			INT(6) NOT NULL AUTO_INCREMENT,
  MAIL_NO 			INT(6) NOT NULL,
  ORIGIN_NAME 		VARCHAR(300),
  CHANGE_NAME 		VARCHAR(300),
  MAIL_PATH 		VARCHAR(200),
  UPLOAD_DATE 		DATETIME,
  HAS_THUMBNAIL 	INT(1),
  PRIMARY KEY (FILE_NO),
  FOREIGN KEY (MAIL_NO) REFERENCES `MAIL` (MAIL_NO) ON DELETE CASCADE
) ;

CREATE TABLE MAIL_SUMMER_IMAGE(
  MAIL_NO 			INT(6) NOT NULL,
  FILESYSTEM 		VARCHAR(40),
  FOREIGN KEY (MAIL_NO) REFERENCES `MAIL` (MAIL_NO) ON DELETE CASCADE
) ;

CREATE TABLE ANONY(
  ANONY_NO 			INT(6) NOT NULL AUTO_INCREMENT,
  ANONY_TITLE 		VARCHAR(80),
  ANONY_CONTENT 	VARCHAR(4000),
  CREATE_DATE 		DATETIME,
  EMP_NO 		INT(8),
  PRIMARY KEY (ANONY_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE UN_CMT(
  UN_CMT_NO 		INT(6) NOT NULL AUTO_INCREMENT,
  ANONY_NO 			INT(6) NOT NULL,
  CREATE_DATE 		DATETIME,
  UN_CMT_CONTENT 	VARCHAR(700),
  STATE 			INT(1),
  DEPTH 			INT(1),
  GROUP_NO 			INT,
  EMP_NO 			INT(8),
  PRIMARY KEY (UN_CMT_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE NOTIC(
  NOTIC_NO 			INT(6) NOT NULL AUTO_INCREMENT,
  EMP_NO 			INT(8),
  BOARD_TITLE 		VARCHAR(60),
  BOARD_CONTENT 	VARCHAR(4000),
  CREATE_DATE 		DATETIME,
  MODIFY_DATE 		DATETIME,
  BOARD_TOP 		VARCHAR(1),
  HIT 				INT,
  PRIMARY KEY (NOTIC_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE BOARD(
  BOARD_NO 			INT(6) NOT NULL AUTO_INCREMENT,
  EMP_NO 			INT(8),
  DEPT_NAME			VARCHAR(20),
  BOARD_TITLE 		VARCHAR(60),
  BOARD_CONTENT 	VARCHAR(4000),
  CREATE_DATE 		DATETIME,
  MODIFY_DATE 		DATETIME,
  HIT 				INT,
  DEPT_NO 			INT,
  STATE 			INT(1),
  PRIMARY KEY (BOARD_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE LOVES(
  BOARD_NO 			INT(6) NOT NULL,
  EMP_NO 			INT(8) NOT NULL,
  MARK_DATE 		DATETIME        NOT NULL,
  FOREIGN KEY (BOARD_NO) REFERENCES `BOARD` (BOARD_NO) ON DELETE CASCADE,
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
) ;

CREATE TABLE COMMENTS(
  COMMENT_NO 			INT(6) NOT NULL AUTO_INCREMENT,
  ANONY_NO 			INT(6) NOT NULL,
  EMP_NO 			INT(8) NULL,
  CREATE_DATE 		DATETIME,
  CONTENT 		VARCHAR(700),
  STATE 			INT(1),
  DEPTH 			INT(1),
  GROUP_NO 			INT DEFAULT 0,
  PRIMARY KEY (COMMENT_NO),
  FOREIGN KEY (ANONY_NO) REFERENCES `ANONY` (ANONY_NO) ON DELETE CASCADE,
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE DEPTHRCOMMENT(
  CMT_NO 		INT(6) NOT NULL AUTO_INCREMENT,
  BOARD_NO 			INT(6) NOT NULL,
  EMP_NO 			INT(8) NULL,
  CREATE_DATE 		DATETIME,
  CONTENT 		VARCHAR(700),
  STATE 			INT(1),
  DEPTH 			INT(1),
  GROUP_NO 			INT DEFAULT 0,
  PRIMARY KEY (CMT_NO),
  FOREIGN KEY (BOARD_NO) REFERENCES `BOARD` (BOARD_NO) ON DELETE CASCADE,
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE UPLOAD(
  UPLOAD_NO 		INT(6) NOT NULL AUTO_INCREMENT,
  EMP_NO 			INT(8) NULL,
  BOARD_TITLE 		VARCHAR(700),
  BOARD_CONTENT 	VARCHAR(4000),
  CREATE_DATE 		DATETIME,
  MODIFY_DATE 		DATETIME,
  HIT 				INT,
  PRIMARY KEY (UPLOAD_NO),
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE ATTACH(
  ATTACH_NO 		INT(6) NOT NULL AUTO_INCREMENT,
  UPLOAD_NO 		INT(6) NOT NULL,
  EMP_NO 			INT(8) NULL,
  PATH 			VARCHAR(300),
  ORIGIN 		VARCHAR(300),
  FILESYSTEM 	VARCHAR(300),
  PRIMARY KEY (ATTACH_NO),
  FOREIGN KEY (UPLOAD_NO) REFERENCES `UPLOAD` (UPLOAD_NO) ON DELETE CASCADE,
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

CREATE TABLE SUMMERNOTE_IMAGE(
  UPLOAD_NO 		INT(6) NOT NULL,
  FILESYSTEM 	VARCHAR(300),
  FOREIGN KEY (UPLOAD_NO) REFERENCES `UPLOAD` (UPLOAD_NO) ON DELETE CASCADE
) ;

CREATE TABLE ACCESS_LOG(
	ACCESS_LOG_NO		INT NOT NULL AUTO_INCREMENT,
    EMP_NO				INT NOT NULL,
    LAST_LOGIN_DATE		DATETIME,
    PRIMARY KEY (ACCESS_LOG_NO),
    FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
);

CREATE TABLE PROF_IMAGE(
    IMG_NO 			INT NOT NULL AUTO_INCREMENT,
    EMP_NO 			INT(8) NOT NULL,  -- 외래키
    PROF_PATH 		VARCHAR(300) NULL,       -- 파일의 경로
    PROF_ORIGIN 	VARCHAR(300) NULL,
    PROF_FILESYSTEM VARCHAR(40),
    PRIMARY KEY (IMG_NO),
    FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE CASCADE
);


CREATE TABLE APPROVAL(
  AP_NO 		INT(20) NOT NULL AUTO_INCREMENT,
  DEPT_NO 		INT(6) NOT NULL,
  EMP_NO 		INT(8) NULL,
  APTITLE 		VARCHAR(50) NOT NULL,
  APDATE 		DATETIME DEFAULT NOW(),
  APCONTENT 	VARCHAR(1800),
  APPERSON 		VARCHAR(20),
  APSTATE 		INT(2) DEFAULT 0 NOT NULL,
  APREJECTION 	VARCHAR(50),
  APPLACE 		VARCHAR(50),
  APATTEND 		VARCHAR(50),
  APDEC 		VARCHAR(100),
  APETC 		VARCHAR(100),
  APFORMAT 		VARCHAR(50),
  APDRAFTER 	VARCHAR(50),
  APPTITLE 		VARCHAR(50),
  PRIMARY KEY (AP_NO),
  FOREIGN KEY (DEPT_NO) REFERENCES `DEPARTMENTS` (DEPT_NO) ON DELETE CASCADE,
  FOREIGN KEY (EMP_NO) REFERENCES `EMPLOYEES` (EMP_NO) ON DELETE SET NULL
) ;

INSERT INTO DEPARTMENTS(DEPT_NAME) VALUES('인사총무부');
INSERT INTO DEPARTMENTS(DEPT_NAME) VALUES('재무회계부');
INSERT INTO DEPARTMENTS(DEPT_NAME) VALUES('영업부');

INSERT INTO EMP_POSITION(JOB_NAME) VALUES('대표');
INSERT INTO EMP_POSITION(JOB_NAME) VALUES('부장');
INSERT INTO EMP_POSITION(JOB_NAME) VALUES('차장');
INSERT INTO EMP_POSITION(JOB_NAME) VALUES('과장');
INSERT INTO EMP_POSITION(JOB_NAME) VALUES('대리');
INSERT INTO EMP_POSITION(JOB_NAME) VALUES('사원');

INSERT INTO EMPLOYEES
	(EMP_NO, EMP_PW, NAME, BIRTHYEAR, BIRTHDAY, JOIN_DATE, PROF_IMG, INFO_MODIFY_DATE,SALARY, JOB_NO, DEPT_NO, PHONE , SESSION_ID, SESSION_LIMIT_DATE)
VALUES
	('22110001', '7DAEEEF4 5D9412A8FBEE58DE2DAEEB1A082ACE7EB F8365D53080394B7C7F23', '관리자', NULL, NULL, NOW(), NULL, NOW(), '0', '2', '10', '01086211328', NULL, NOW());
    
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120001@sharegram.com';
 
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120002@sharegram.com';
 
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120003@sharegram.com';
 
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120004@sharegram.com';
 
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120005@sharegram.com';
 
DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120006@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120007@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120008@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120009@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120010@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '23010011@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '23010012@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '23010013@sharegram.com';
 
 DELETE
  FROM JAMES_USER
 WHERE USER_NAME = '22120006@sharegram.com';
    
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 14일 08시 55분' , '2022년 12월 14일 17시 55분' ,'정상 출근' );  
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 15일 09시 12분' , '2022년 12월 15일 19시 03분' ,'지각' );  
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 16일 08시 32분' , '2022년 12월 16일 18시 02분' ,'정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 17일 08시 55분' , '2022년 12월 17일 18시 01분' ,'정상 출근' );  
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 18일 08시 50분' , '2022년 12월 18일 20시 05분' ,'정상 출근' );             
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 19일 09시 48분' , '2022년 12월 19일 18시 03분' ,'지각' );            
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 20일 08시 48분' , '2022년 12월 20일 18시 01분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 21일 08시 42분' , '2022년 12월 21일 17시 51분' , '정상 출근' );             
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS, EARLY_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 22일 08시 32분' ,  '2022년 12월 22일 14시 51분' , '정상 출근' , '조퇴' );                    
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 23일 08시 42분' ,  '2022년 12월 23일 21시 20분' , '정상 출근' );

INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 24일 08시 42분' ,  '2022년 12월 24일 18시 00분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 24일 08시 45분' ,  '2022년 12월 24일 17시 50분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010003 , '2022년 12월 24일 08시 42분' ,  '2022년 12월 24일 17시 55분' , '정상 출근' );  
 
 INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 25일 08시 42분' ,  '2022년 12월 25일 17시 55분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 25일 08시 4\55분' ,  '2022년 12월 25일 17시 52분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010003 , '2022년 12월 25일 08시 8\52분' ,  '2022년 12월 25일 17시 58분' , '정상 출근' ); 
            
 INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010001 , '2022년 12월 26일 08시 42분' ,  '2022년 12월 26일 17시 52분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010002 , '2022년 12월 26일 08시 4\55분' ,  '2022년 12월 26일 17시 58분' , '정상 출근' );
INSERT INTO ATTENDANCE
            ( EMP_NO , ATT_START , ATT_END, ATT_STATUS)
        VALUES
            ( 23010003 , '2022년 12월 26일 08시 8\52분' ,  '2022년 12월 26일 17시 59분' , '정상 출근' );             
 
 
 
 
 
 
commit;

    
    
COMMIT;